source 'https://github.com/CocoaPods/Specs.git'

target 'MSAppModuleKit_Example', :exclusive => true do
    pod "MSAppModuleKit", :path => "../"
    pod "MSAppModuleDemo1", :path => "../"
    
end

#target 'MSAppModuleKit_Tests', :exclusive => true do
#    pod "MSAppModuleKit", :path => "../"
#    pod "MSAppModuleDemo1", :path => "../"
#    
#    #  pod 'Specta'
#    #  pod 'Expecta'
#    #  pod 'FBSnapshotTestCase'
#    #  pod 'Expecta+Snapshots'
#end
