source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MSAppModuleKit_Example', :exclusive => true do
  pod "MSAppModuleKit", :path => "../"
end

target 'MSAppModuleKit_Tests', :exclusive => true do
  pod "MSAppModuleKit", :path => "../"

  pod 'FBSnapshotTestCase'
end
