# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod ‘MSAppModuleKit’, :path=> '../'
    
  target 'ExampleSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
